"""change table name

Revision ID: 94afa438efd6
Revises: c293dd916f33
Create Date: 2025-08-30 22:51:44.335869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94afa438efd6'
down_revision: Union[str, None] = 'c293dd916f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('결제대기', '결제완료', '상품준비중', '배송중', '배송완료', '구매확정', '주문취소', name='order_status'), nullable=False),
    sa.Column('subtotal_price', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('order_coupon_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_name', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('zipcode', sa.String(length=16), nullable=False),
    sa.Column('address_line1', sa.String(length=128), nullable=False),
    sa.Column('address_line2', sa.String(length=128), nullable=True),
    sa.Column('order_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_coupon_id'], ['CouponWallet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Order',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.ENUM('결제대기', '결제완료', '상품준비중', '배송중', '배송완료', '구매확정', '주문취소'), nullable=False),
    sa.Column('subtotal_price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('discount_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('total_price', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('order_coupon_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('recipient_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('address_line1', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('address_line2', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('order_memo', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['order_coupon_id'], ['CouponWallet.id'], name='Order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Orders')
    # ### end Alembic commands ###
