"""change cartitem column value to id

Revision ID: 65ae70e98ab5
Revises: 6ea754cf1b5c
Create Date: 2025-09-17 23:26:53.885828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65ae70e98ab5'
down_revision: Union[str, None] = '6ea754cf1b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItem', sa.Column('option_type_1_id', sa.String(length=36), nullable=True))
    op.add_column('CartItem', sa.Column('option_1_id', sa.String(length=36), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_2_id', sa.String(length=36), nullable=True))
    op.add_column('CartItem', sa.Column('option_2_id', sa.String(length=36), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_3_id', sa.String(length=36), nullable=True))
    op.add_column('CartItem', sa.Column('option_3_id', sa.String(length=36), nullable=True))
    op.drop_column('CartItem', 'option_type_1')
    op.drop_column('CartItem', 'option_2')
    op.drop_column('CartItem', 'option_type_3')
    op.drop_column('CartItem', 'option_type_2')
    op.drop_column('CartItem', 'option_1')
    op.drop_column('CartItem', 'option_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItem', sa.Column('option_3', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_1', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_2', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_3', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_2', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_1', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('CartItem', 'option_3_id')
    op.drop_column('CartItem', 'option_type_3_id')
    op.drop_column('CartItem', 'option_2_id')
    op.drop_column('CartItem', 'option_type_2_id')
    op.drop_column('CartItem', 'option_1_id')
    op.drop_column('CartItem', 'option_type_1_id')
    # ### end Alembic commands ###
