"""Fix review content field

Revision ID: c9bdc8f6f39a
Revises: b26ee07ff310
Create Date: 2025-06-27 22:05:37.247824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9bdc8f6f39a'
down_revision: Union[str, None] = 'b26ee07ff310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProductReview', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProductReview', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
