"""add product option type table

Revision ID: 99eb7ea1db0b
Revises: 55af0332f666
Create Date: 2025-09-09 21:13:57.344156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99eb7ea1db0b'
down_revision: Union[str, None] = '55af0332f666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductOptionType',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('option_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ProductOption', sa.Column('product_option_type_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'ProductOption', 'ProductOptionType', ['product_option_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProductOption', type_='foreignkey')
    op.drop_column('ProductOption', 'product_option_type_id')
    op.drop_table('ProductOptionType')
    # ### end Alembic commands ###
