"""fix provider id len

Revision ID: deb331cc3e8a
Revises: a9e0f3350477
Create Date: 2025-09-06 19:03:51.755088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'deb331cc3e8a'
down_revision: Union[str, None] = 'a9e0f3350477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'provider_id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'provider_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
