"""Add user name to product review

Revision ID: 69f3aa60b551
Revises: 907c159c969d
Create Date: 2025-06-28 21:47:35.687479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f3aa60b551'
down_revision: Union[str, None] = '907c159c969d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TABLE ProductReview 
        ADD COLUMN user_name VARCHAR(32) NOT NULL AFTER user_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProductReview', 'user_name')
    # ### end Alembic commands ###
