"""add order coupon tables

Revision ID: c293dd916f33
Revises: 3ec43642c2e7
Create Date: 2025-08-30 22:48:34.167146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c293dd916f33'
down_revision: Union[str, None] = '3ec43642c2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coupon',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('discount_type', sa.Enum('비율', '정액', name='discount_type'), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=7, scale=0), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=7, scale=0), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=7, scale=0), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('CouponWallet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['Coupon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('결제대기', '결제완료', '상품준비중', '배송중', '배송완료', '구매확정', '주문취소', name='order_status'), nullable=False),
    sa.Column('subtotal_price', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('order_coupon_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_name', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('zipcode', sa.String(length=16), nullable=False),
    sa.Column('address_line1', sa.String(length=128), nullable=False),
    sa.Column('address_line2', sa.String(length=128), nullable=True),
    sa.Column('order_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_coupon_id'], ['CouponWallet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order')
    op.drop_table('CouponWallet')
    op.drop_table('Coupon')
    # ### end Alembic commands ###
