"""add payment & pointtransaction

Revision ID: 2e4d45c6609f
Revises: e3a232039c0e
Create Date: 2025-09-03 01:06:35.952020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4d45c6609f'
down_revision: Union[str, None] = 'e3a232039c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('대기중', '성공', '실패', name='status'), nullable=True),
    sa.Column('method', sa.Enum('카드', '휴대폰', '카카오페이', '토스페이', '포인트', name='method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('PointTransaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('적립', '사용', '환불', name='type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PointTransaction')
    op.drop_table('Payment')
    # ### end Alembic commands ###
