"""change column order

Revision ID: 1c77e38ff8ec
Revises: 627a6f2445d1
Create Date: 2025-04-27 22:12:18.969600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77e38ff8ec'
down_revision: Union[str, None] = '627a6f2445d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE User MODIFY COLUMN provider_id VARCHAR(32) AFTER provider;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE User MODIFY COLUMN provider_id VARCHAR(32) FIRST;')
    # ### end Alembic commands ###
