"""change column order

Revision ID: aa123ef1bdd1
Revises: 304a4f1accba
Create Date: 2025-04-27 21:30:38.832853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa123ef1bdd1'
down_revision: Union[str, None] = '304a4f1accba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE User MODIFY COLUMN provider VARCHAR(32) AFTER name;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE User MODIFY COLUMN provider VARCHAR(32) FIRST;')
    # ### end Alembic commands ###
