"""fix order merchant id column

Revision ID: 494a08d5e0fb
Revises: 1318866d8095
Create Date: 2025-09-10 16:49:08.779174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '494a08d5e0fb'
down_revision: Union[str, None] = '1318866d8095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('OrderItem', 'product_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('Payment', 'merchant_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payment', 'merchant_id',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('OrderItem', 'product_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
