"""fix payment method

Revision ID: 933c414961d1
Revises: deb331cc3e8a
Create Date: 2025-09-08 00:18:05.334573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '933c414961d1'
down_revision: Union[str, None] = 'deb331cc3e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payment', 'method',
               existing_type=mysql.ENUM('카드', '휴대폰', '카카오페이', '토스페이', '포인트'),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payment', 'method',
               existing_type=sa.String(length=16),
               type_=mysql.ENUM('카드', '휴대폰', '카카오페이', '토스페이', '포인트'),
               existing_nullable=False)
    # ### end Alembic commands ###
