"""add useraddress table

Revision ID: cbcb35f6112c
Revises: 9a802d269e03
Create Date: 2025-09-08 01:47:22.642858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcb35f6112c'
down_revision: Union[str, None] = '9a802d269e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAddress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_name', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('zipcode', sa.String(length=16), nullable=False),
    sa.Column('address_line1', sa.String(length=128), nullable=False),
    sa.Column('address_line2', sa.String(length=128), nullable=True),
    sa.Column('order_memo', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAddress')
    # ### end Alembic commands ###
