"""add merchant id column to payment

Revision ID: 9a802d269e03
Revises: 933c414961d1
Create Date: 2025-09-08 00:43:02.292014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a802d269e03'
down_revision: Union[str, None] = '933c414961d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('merchant_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payment', 'merchant_id')
    # ### end Alembic commands ###
