"""add product name to orderitem

Revision ID: 1318866d8095
Revises: 9f369dbc1cc9
Create Date: 2025-09-09 23:31:00.905567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1318866d8095'
down_revision: Union[str, None] = '9f369dbc1cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderItem', sa.Column('product_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderItem', 'product_name')
    # ### end Alembic commands ###
