"""create product table

Revision ID: cc521f326ff2
Revises: 6f891934e0be
Create Date: 2025-05-12 16:21:33.780113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc521f326ff2'
down_revision: Union[str, None] = '6f891934e0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price_whole', sa.Integer(), nullable=False),
    sa.Column('price_sell', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_main', sa.String(length=32), nullable=False),
    sa.Column('category_sub', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_number')
    )
    op.execute(
        'ALTER TABLE Product MODIFY COLUMN product_number INT NOT NULL AUTO_INCREMENT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Product')
    # ### end Alembic commands ###
