"""add refund table

Revision ID: a31a39118bf9
Revises: 65ae70e98ab5
Create Date: 2025-09-18 02:42:20.100662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31a39118bf9'
down_revision: Union[str, None] = '65ae70e98ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Refund',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('요청', '완료', '거부', name='status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('restore_point_amount', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['Payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Refund')
    # ### end Alembic commands ###
