"""refactor cartitem columns

Revision ID: 6ea754cf1b5c
Revises: 494a08d5e0fb
Create Date: 2025-09-17 23:18:36.233139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ea754cf1b5c'
down_revision: Union[str, None] = '494a08d5e0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItem', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('CartItem', sa.Column('option_type_1', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_1', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('is_option_1_active', sa.Boolean(), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_2', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_2', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('is_option_2_active', sa.Boolean(), nullable=True))
    op.add_column('CartItem', sa.Column('option_type_3', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('option_3', sa.String(length=32), nullable=True))
    op.add_column('CartItem', sa.Column('is_option_3_active', sa.Boolean(), nullable=True))
    op.drop_column('CartItem', 'product_option_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CartItem', sa.Column('product_option_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('CartItem', 'is_option_3_active')
    op.drop_column('CartItem', 'option_3')
    op.drop_column('CartItem', 'option_type_3')
    op.drop_column('CartItem', 'is_option_2_active')
    op.drop_column('CartItem', 'option_2')
    op.drop_column('CartItem', 'option_type_2')
    op.drop_column('CartItem', 'is_option_1_active')
    op.drop_column('CartItem', 'option_1')
    op.drop_column('CartItem', 'option_type_1')
    op.drop_column('CartItem', 'is_active')
    # ### end Alembic commands ###
