"""fix order related tables

Revision ID: a9e0f3350477
Revises: 2e4d45c6609f
Create Date: 2025-09-03 02:37:10.464933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9e0f3350477'
down_revision: Union[str, None] = '2e4d45c6609f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CouponWallet', 'order_id')
    op.add_column('OrderItem', sa.Column('coupon_wallet_id', sa.String(length=36), nullable=True))
    op.add_column('OrderItem', sa.Column('status', sa.Enum('주문완료', '주문취소', '환불', name='status'), nullable=True))
    op.add_column('OrderItem', sa.Column('unit_price', sa.Numeric(precision=10, scale=0), nullable=False))
    op.add_column('OrderItem', sa.Column('coupon_discount_price', sa.Numeric(precision=10, scale=0), nullable=True))
    op.add_column('OrderItem', sa.Column('point_discount_price', sa.Numeric(precision=10, scale=0), nullable=True))
    op.add_column('OrderItem', sa.Column('final_price', sa.Numeric(precision=10, scale=0), nullable=False))
    op.create_foreign_key(None, 'OrderItem', 'CouponWallet', ['coupon_wallet_id'], ['id'])
    op.drop_column('OrderItem', 'price')
    op.add_column('Orders', sa.Column('coupon_discount_price', sa.Numeric(precision=10, scale=0), nullable=True))
    op.add_column('Orders', sa.Column('point_discount_price', sa.Numeric(precision=10, scale=0), nullable=True))
    op.drop_constraint('Orders_ibfk_1', 'Orders', type_='foreignkey')
    op.drop_column('Orders', 'discount_price')
    op.drop_column('Orders', 'order_coupon_id')
    op.alter_column('PointTransaction', 'type',
               existing_type=mysql.ENUM('적립', '사용', '환불'),
               type_=sa.Enum('적립', '사용', '취소', name='type'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PointTransaction', 'type',
               existing_type=sa.Enum('적립', '사용', '취소', name='type'),
               type_=mysql.ENUM('적립', '사용', '환불'),
               existing_nullable=False)
    op.add_column('Orders', sa.Column('order_coupon_id', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('Orders', sa.Column('discount_price', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.create_foreign_key('Orders_ibfk_1', 'Orders', 'CouponWallet', ['order_coupon_id'], ['id'])
    op.drop_column('Orders', 'point_discount_price')
    op.drop_column('Orders', 'coupon_discount_price')
    op.add_column('OrderItem', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.drop_constraint(None, 'OrderItem', type_='foreignkey')
    op.drop_column('OrderItem', 'final_price')
    op.drop_column('OrderItem', 'point_discount_price')
    op.drop_column('OrderItem', 'coupon_discount_price')
    op.drop_column('OrderItem', 'unit_price')
    op.drop_column('OrderItem', 'status')
    op.drop_column('OrderItem', 'coupon_wallet_id')
    op.add_column('CouponWallet', sa.Column('order_id', mysql.VARCHAR(length=36), nullable=True))
    # ### end Alembic commands ###
