"""modify user table

Revision ID: 304a4f1accba
Revises: 55ddaf85622a
Create Date: 2025-04-27 21:27:16.256262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '304a4f1accba'
down_revision: Union[str, None] = '55ddaf85622a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('provider', sa.String(length=32), nullable=True))
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_column('User', 'provider')
    # ### end Alembic commands ###
