"""fix orderitem table

Revision ID: 9f369dbc1cc9
Revises: 99eb7ea1db0b
Create Date: 2025-09-09 22:08:43.974641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f369dbc1cc9'
down_revision: Union[str, None] = '99eb7ea1db0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CouponWallet_ibfk_2', 'CouponWallet', type_='foreignkey')
    op.add_column('OrderItem', sa.Column('option_1_type', sa.String(length=32), nullable=True))
    op.add_column('OrderItem', sa.Column('option_1_value', sa.String(length=32), nullable=True))
    op.add_column('OrderItem', sa.Column('option_2_type', sa.String(length=32), nullable=True))
    op.add_column('OrderItem', sa.Column('option_2_value', sa.String(length=32), nullable=True))
    op.add_column('OrderItem', sa.Column('option_3_type', sa.String(length=32), nullable=True))
    op.add_column('OrderItem', sa.Column('option_3_value', sa.String(length=32), nullable=True))
    op.drop_constraint('OrderItem_ibfk_2', 'OrderItem', type_='foreignkey')
    op.drop_constraint('Orders_ibfk_2', 'Orders', type_='foreignkey')
    op.drop_constraint('PointTransaction_ibfk_2', 'PointTransaction', type_='foreignkey')
    op.alter_column('ProductOption', 'product_option_type_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint('ProductOption_ibfk_2', 'ProductOption', type_='foreignkey')
    op.create_foreign_key(None, 'ProductOption', 'ProductOptionType', ['product_option_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProductOption', type_='foreignkey')
    op.create_foreign_key('ProductOption_ibfk_2', 'ProductOption', 'ProductOptionType', ['product_option_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ProductOption', 'product_option_type_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key('PointTransaction_ibfk_2', 'PointTransaction', 'User', ['user_id'], ['id'])
    op.create_foreign_key('Orders_ibfk_2', 'Orders', 'User', ['user_id'], ['id'])
    op.create_foreign_key('OrderItem_ibfk_2', 'OrderItem', 'Product', ['product_id'], ['id'])
    op.drop_column('OrderItem', 'option_3_value')
    op.drop_column('OrderItem', 'option_3_type')
    op.drop_column('OrderItem', 'option_2_value')
    op.drop_column('OrderItem', 'option_2_type')
    op.drop_column('OrderItem', 'option_1_value')
    op.drop_column('OrderItem', 'option_1_type')
    op.create_foreign_key('CouponWallet_ibfk_2', 'CouponWallet', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
