name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Internal Instance
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Host and execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_KEY }}
          script_stop: true  
          script: |
            cd birdie
            git pull
            echo "SUCCESSFULLY FINISHED"